# updated: 2022.11.02
qcloudsms-py: 0.1.4 # 已停止维护, 需适配py3.9 https://github.com/qcloudsms/qcloudsms_py
django-crontab: 0.7.1 # 已停止维护, https://github.com/kraiz/django-crontab
mysql-connector-python: 8.0.29 # 被依赖特定的版本, mysql API
#----------------------------
beautifulsoup4: 4.11.1 # 处理HTML
colorama: 0.4.6 # 彩色print
coverage: 6.5.0 # 计算覆盖率
Django: 4.1.2 # 基础框架
djangorestframework: 3.14.0 # REST framework for Django
django-compressor: 4.1 # 压缩css/js
django-cors-headers: 3.13.0 # 跨域访问之headers
django-cors-middleware: 1.5.0 # 跨域访问之middleware
django-debug-toolbar: 3.7.0 # 调试工具
django-filter: 22.1 # django filtering support
django-haystack: 3.2.1 # 全局搜索
django-import-export: 3.0.1 # 数据导入导出
django-jazzmin: 2.5.0 # 非常美观的django-adminUI库
django-matomo: 0.1.6 # 网站分析
django-recaptcha: 3.0.0 # Google Recaptcha验证
django-redis: 5.2.0 # django的全局redis
django-user-agents: 0.4.0 # 用户代理处理
fabric: 2.7.1 # 自动化管理项目
Faker: 15.1.1 # 测试数据生成
fake-useragent: 0.1.11 # 用户代理模拟
fontawesomefree: 6.2.0 # fontawesome free字体管理
gunicorn: 20.1.0 # 动态web服务器
igraph: 0.10.2 # 图和网络分析工具
ipykernel: 6.16.2 # python 笔记本
ipython: 8.6.0 # 交互式python
jieba: 0.42.1 # 中文分词
lxml: 4.9.1 # 用作bs4的解析器
matplotlib: 3.6.1 # 绘图库
Markdown: 3.4.1 # markdown支持
mysqlclient: 2.1.1 # mysql的pythonAPI
mysql-to-sqlite3: 1.4.14 # mysql -> sqlite3
networkx: 2.8.7 # 图和网络分析工具
numpy: 1.23.4 # 矩阵计算
pandas: 1.5.1 # 数据处理
Pillow: 9.3.0 # 图像处理
pip: 22.3 # 包管理工具
pipdeptree: 2.3.3 # 获取python依赖关系
pip-review: 1.2.0 # 升级第三方包
pydub: 0.25.1 # 音频处理库
pymdown-extensions: 9.7 # 实用的Python-Markdown扩展
python-dotenv: 0.21.0 # 环境变量获取
qrcode: 7.3.1 # 二维码
readtime: 2.0.0 # 阅读时间计算
redis: 4.3.4 # redisAPI
requests: 2.28.1 # web请求
scipy: 1.9.3 # 科学计算
sh: 1.14.3 # 执行shell命令
sqlite3-to-mysql: 1.4.16 # sqlite迁移到mysql
torch: 1.13.0 # 深度学习框架
torchaudio: 0.13.0 # 音频相关数据集、模型类、预训练模型
torchvision: 0.14.0 # 图片相关数据集、模型类、预训练模型
Whoosh: 2.7.4 # 站内搜索
xlrd: 2.0.1 # NOTE: 被django-import-export所依赖
xlwt: 1.3.0 # NOTE: 被django-import-export所依赖
